name: icildice
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8.20
  - pip:
    - torch==2.4.1
    - numpy==1.23.5
    - gymnasium==0.28.0
    - huggingface-hub==0.34.4
    - wandb==0.21.0
    - pickle5==0.0.11
    - pyyaml==6.0.2
    - python-dateutil==2.9.0
