method: BCFiltered
env_id: SafetyPointCircle1-v0
device: cuda
use_wandb: False

wandb:
  project: 'offline-icil-bctest'
  entity: 'tzs930'

dataset:
  dataset_path: 'dataset/SafetyPointCircle1-v0'
  expert:
    types:         ['safe-expert-v0', 'unsafe-expert-v0']
    start_indices: [0, 0]
    num_trajs:     [0, 10]
  safe:
    types:         ['safe-expert-v0', 'safe-medium-v0']
    start_indices: [250, 0]
    num_trajs:     [0, 10]
  mixed:
    types: ['safe-expert-v0', 'safe-medium-v0', 'unsafe-expert-v0', 'unsafe-medium-v0']
    start_indices: [500, 500, 500, 500]
    num_trajs:     [500, 500, 500, 500]

replay_buffer:
  class: 'MDPReplayBuffer'
  max_replay_buffer_size: 10000000
  standardize_obs: False
  standardize_act: False

policy:
  class: 'GaussianPolicy'
  layer_sizes: [256, 256]

train:
  seed: 0
  gamma: 0.99
  lr: 3e-5
  lr_disc: 3e-5
  total_iteration: 1000000
  eval_freq: 5000
  batch_size: 512
  save_policy_path: results/SafetyPointCircle1-v0/bc
  num_evals: 10
  disc_gp_weight: 0.0
  disc_hidden_size: [256, 256]
  disc_quantile: 0.99
  threshold_update_freq: 100
  disc_learning_during_train: True
  