method: DemoDICESafe
env_id: SafetyPointCircle1-v0
device: cuda
use_wandb: True

wandb:
  project: 'offline-icil-250820'
  entity: 'tzs930'

dataset:
  dataset_path: 'dataset/SafetyPointCircle1-v0'
  expert:
    types: ['safe-expert-v0', 'unsafe-expert-v0'] #, 'safe-expert-v0']
    start_indices: [0, 0] #, 0]
    num_trajs: [50, 50]
  safe:
    types: ['safe-expert-v0', 'safe-medium-v0']
    start_indices: [500, 0]
    num_trajs: [500, 500]
  mixed:
    types: []
    start_indices: []
    num_trajs: null

replay_buffer:
  class: 'MDPReplayBuffer'
  max_replay_buffer_size: 1000000
  standardize_obs: False
  standardize_act: False

policy:
  class: 'GaussianPolicy'
  layer_sizes: [256, 256]

train:
  seed: 0
  gamma: 0.99
  alpha: 0.1 # Dataset Regularization Coefficient
  lr: 3e-5
  lr_nu: 3e-4
  lr_disc: 3e-5
  lr_prior: null
  lr_lambda: null
  disc_gp_weight: 10.0
  disc_steps: 1
  total_iteration: 1000000
  eval_freq: 10000
  batch_size: 512
  save_policy_path: null
  num_evals: 10
  pretrain_steps: 0
  n_prior_nets: null
  prior_output_size: null
  uncertainty_safe_quantile: null
  uncertainty_threshold_update_freq: null
  uncertainty_gp_weight: null