method: IcilDICEv3
env_id: SafetyPointCircle1-v0
device: cuda
use_wandb: True #True

wandb:
  project: 'offline-icil-250826'
  entity: 'tzs930'

dataset:
  dataset_path: 'dataset/SafetyPointCircle1-v0'
  expert:
    types: ['safe-expert-v0', 'unsafe-expert-v0'] #, 'safe-expert-v0']
    start_indices: [0, 0] #, 0]
    num_trajs:     [250, 250]
  safe:
    types: ['safe-expert-v0', 'safe-medium-v0']
    start_indices: [500, 0]
    num_trajs:     [250, 250]
  mixed:
    types: ['safe-expert-v0', 'safe-medium-v0', 'unsafe-expert-v0', 'unsafe-medium-v0']
    start_indices: [500, 500, 500, 500]
    num_trajs:     [500, 500, 500, 500]

replay_buffer:
  class: 'MDPReplayBuffer'
  max_replay_buffer_size: 10000000
  standardize_obs: False
  standardize_act: False

policy:
  class: 'GaussianPolicy'
  layer_sizes: [256, 256]

train:
  seed: 0
  gamma: 0.99
  alpha: 0. # Dataset Regularization Coefficient
  lr: 3e-4
  lr_nu: 3e-4
  lr_disc: 3e-4
  lr_prior: 3e-4
  lr_lambda: 3e-4
  nu_hidden_size: [256, 256]
  nu_gp_weight: 10.0
  disc_hidden_size: [256, 256]
  disc_gp_weight: 10.0  # Gradient penalty coefficient
  disc_steps: 1
  uc_disc_hidden_size: [256, 256]
  uc_disc_gp_weight: 10.0
  total_iteration: 1000000
  eval_freq: 10000
  batch_size: 512
  save_policy_path: null
  num_evals: 10
  pretrain_steps: 0
  n_prior_nets: 2
  prior_output_size: 10
  prior_net_size: [64, 64]
  fittor_net_size: [256, 256] # More larger
  uncertainty_safe_quantile: 0.99
  uncertainty_threshold_update_freq: 100
  uncertainty_gp_weight: 10.0
  indicator_weight: 1.0
  lambda_starts: 1.0
  use_soft_indicator: False
  class_prior: 0.5
  # prior_learning_during_train: False